accounts/urls.py
from django.conf.urls import url
from.views import *

app_name = 'accounts'


urlpatterns = [


    url(r'^login/$', login_view, name='login'),
    url(r'^register/$', register_view, name='register'),
    url(r'^logout/$', logout_view, name='logout'),

]

blog/urls.py
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from blog import settings
from home.views import home_view
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    #url(r'^$', home_view),
    url(r'^home/', include('home.urls')),

    url(r'^post/', include('postt.urls')),

    url(r'^accounts/', include('accounts.urls')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.conf.urls import url
from.views import *

app_name = 'home'


urlpatterns = [


    url(r'', home_view, name='home'),

]

postt/urls.py
from django.conf.urls import url
from . import views

app_name = 'post'

urlpatterns = [

    url(r'^index/$', views.post_index, name='index'),
    url(r'^(?P<id>\d+)/detail/$', views.post_detail, name='detail'),
    url(r'^create/$', views.post_create, name='create'),
    url(r'^(?P<id>\d+)/update/$', views.post_update, name='update'),
    url(r'^(?P<id>\d+)/delete/$', views.post_delete, name='delete'),
]

home/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

home/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, HttpResponse

def home_view(request):

    if request.user.is_authenticated:
        context = {
            'isim': 'm0m0',
        }
    else:
        context = {
            'isim': 'misafir',
        }
    return render(request, 'home.html', context)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" name="viewport" content="width=device-width, inital-scale=1">
    <title>{% block title %}{% endblock %}BluTv</title>

    <!-- Latest compiled and minified CSS -->

    <!-- Latest compiled and minified JavaScript -->

</head>
<body>

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
      integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap-theme.min.css"
      integrity="sha384-6pzBo3FDv/PJ8r2KRkGHifhEocL+1X2rVCTTkUfGk7/0pbek5mMa1upzvWbrUbOZ" crossorigin="anonymous">
<link rel="stylesheet" href="{% static '/css/style.css' %}">
{% include 'header.html' %}

{% include 'messages.html' %}



{% block body %}

{% endblock %}

<script src="{% static 'js/jquery.min.js' %}"></script>

<script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
        integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd"
        crossorigin="anonymous"></script>

</body>
</html>

templates/header.html
<!-- Navbar Start -->
<nav class="navbar navbar-inverse navbar-fixed-top " role="banner">
    <div class="container">

        <div class="navbar-header">

            <!-- Telefon ekranları için menü butonu -->
            <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

            <!-- İsim Soyisim veya Marka İsmi -->
            <a href="{% url 'home:home' %}" class="navbar-brand">GİYBET</a>
        </div>

        <nav class="collapse navbar-collapse" role="navigation">

            <!-- Arama Çubuğu -->
            <form class="navbar-form navbar-left" role="search" method="GET" action="">
                <div class="input-group">
                    <input class="form-control" type="text" name="q" placeholder="Search on blog" value="{{ request.GET.q }}" >
                    <span class="input-group-btn">
                        <input class="btn btn-default" type="submit" value="Ara">
                    </span>
                </div>
            </form>

            <!-- Temel Sayfalar -->
            <ul class="nav navbar-nav navbar-right">
                    {% if request.user.is_authenticated %}
                    <li><a href="{% url 'post:create' %}">YAZI EKLE</a></li>
                {% endif %}
                <li><a href="{% url 'home:home' %}">Anasayfa</a></li>
                <li><a href="{% url 'post:index' %}">Blog</a></li>
          <!--  <li><a href="#">Hakkımda</a></li>
                <li><a href="#">İletişim</a></li>  -->

                {% if not request.user.is_authenticated %}

                    <li><a href="{% url 'accounts:register' %}">üye ol</a> </li>
                    <li><a href="{% url 'accounts:login' %}">giriş</a> </li>

                {% else %}

                    <li><a href="{% url 'accounts:logout' %}">çıkış</a></li>

                {% endif %}

            </ul>

        </nav>

    </div>
</nav>

templates/home.html
{% extends 'base.html' %}

{%block title%} Anasayfa - {{ block.super}}{% endblock %}

{% block body %}

    merhaba, {{isim}}

{% endblock %}

templates/messages.html
    {% if messages %}

        {% for message in messages %}
            <div class="alert alert-success alert-dismissible" role="alert">
              <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    {{ message }}
            </div>
        {% endfor %}

    {% endif %}