blog/urls.py
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from blog import settings
from home.views import home_view
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    #url(r'^$', home_view),
    url(r'^home/', include('home.urls')),

    url(r'^post/', include('postt.urls')),

    url(r'^accounts/', include('accounts.urls')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

postt/urls.py
from django.conf.urls import url
from . import views

app_name = 'post'

urlpatterns = [

    url(r'^index/$', views.post_index, name='index'),
    url(r'^(?P<id>\d+)/detail/$', views.post_detail, name='detail'),
    url(r'^create/$', views.post_create, name='create'),
    url(r'^(?P<id>\d+)/update/$', views.post_update, name='update'),
    url(r'^(?P<id>\d+)/delete/$', views.post_delete, name='delete'),
]

templates/post/comment.html
{% load crispy_forms_tags %}

<form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" class="btn btn-primary" value="yorum ekle">
    <input type="hidden" name="reply_id" value="{{ reply_id }}">
    <input type="hidden" name="replys_id" value="{{ replys_id }}">
</form>

templates/post/detail.html
{% extends 'base.html' %}

{% block body %}



    <div class="container">
        <div class="row">
            <div class=" col-md-6 col-md-offset-3">
                <div class="thumbnail">
                    <div class="caption">
                        {% if post.image %}
                            <img src="{{ post.image.url }}" class="img-responsive">

                        {% endif %}
                        <h3> {{ post.title }} <small>  {{ post.publishing_date| timesince }}prior to</small></h3>
                        <h4>Yazar: {{ post.user.get_full_name }}</h4>
                        <p>{{ post.content|safe|linebreaks|truncatechars:100 }}</p>
                        {% if request.user.is_authenticated %}
                            <a href="{% url 'post:update' id=post.id %}" class="btn btn-default"
                               role="button">güncelle</a>
                            <a href="{% url 'post:delete' id=post.id %}" class="btn btn-danger" role="button">sil</a>
                        {% endif %}
                    </div>
                </div>
                <br><br>
                <hr>
                <h3>yorum ekle:</h3>
                {% include 'post/comment.html' %}
                <hr>
                {% for comment in post.comments.all %}
                    <div class="comments">
                    {% if not comment.reply_id %}
                        <div class="comment">
                            <h4>{{ comment.name }} | <small>{{ comment.created_date|timesince }} önce</small></h4>
                            <p>{{ comment.content|linebreaks }}</p>

                            {% for reply in comment.replies.all %}

                                <li>
                                    Kişi: {{ reply.name }} Cevap: {{ reply.content }}
                                </li>


                            {% endfor %}
                        </div>
                        <br><br>

                        <div style="display: none;" class="answer" id="myDIV-{{ comment.id }}">
                            <h3>cevap ekle:</h3>

                            {% include 'post/comment.html' with reply_id=comment.id %}


                        </div>

                        <br><br>
                        <button onclick="myFunction('myDIV-{{ comment.id }}')">cevap yaz</button>
                        <hr>






                    {% endif %}



                {% endfor %}
                <script>

                    function myFunction(div_id) {
                        var x = document.getElementById(div_id);
                        var comments = document.querySelectorAll(".comments");
                        comments.forEach(function (comment) {
                            var answer = comment.querySelector(".answer");
                            if (answer.id != div_id) {
                                answer.style.display = 'none';
                            } else {
                                answer.style.display = 'block';
                            }


                        });


                    }


                </script>


                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/post/form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-md-offset-3">

                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <h1>Form</h1>
                    {{ form | crispy }}
                    {{ form.media }}
                    <input class="btn btn-primary" type="submit" value="gönder">
                </form>

            </div>
        </div>
    </div>



{% endblock %}

templates/post/index.html
{% extends 'base.html' %}

{% block body  %}

    <div class="container">

    {% for post in posts %}
        <div class="row">
          <div class=" col-md-6 col-md-offset-3">
            <div class="thumbnail">
              <div class="caption">

                   {% if post.image %}
                      <img src="{{ post.image.url }}" class="img-responsive">

                   {%  else %}
                       {{ post.image }}

                   {% endif %}

                    <h3> {{ post.title }} <small>  {{ post.publishing_date| timesince }}prior to</small> </h3>
                    <h4>Yazar: {{ post.user.get_full_name }}</h4>
                    <p>{{ post.content|safe|linebreaks|truncatechars:80}}</p>
                    <p><a href="{% url 'post:detail' id=post.id %}" class="btn btn-primary" role="button">incele</a>
                              {% if request.user.is_authenticated %}
                                <a href="{% url 'post:update' id=post.id %}" class="btn btn-default" role="button">güncelle</a>
                                <a href="{% url 'post:delete' id=post.id %}" class="btn btn-danger" role="button">sil</a>
                              {% endif %}
              </div>
            </div>
          </div>
        </div>

    {% endfor %}
   <!--  <div class="row">
            <div class=" col-md-6 col-md-offset-3">

                 <div class="pagination">
                      <span class="step-links">
                         {% if posts.has_previous %}
                             <a href="?page={{ posts.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">previous</a>

                         {% endif %}

                            <span class="current">
                                Page {{ posts.number }} of {{ posts.paginator.num_pages }}.
                            </span>

                          {% if posts.has_next %}
                              <a href="?page={{ posts.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">next</a>
                          {% endif %}
                    </span>
                </div>
            </div>
     </div> -->
{% endblock %}